baseURL = "https://remoterabbit.github.io"
enableGitInfo = true
languageCode = "en-us"
title = "RemoteRabbit Blog"
theme = "hugo-xterm"
paginate = 20
canonifyurls = true

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        hl_inline = false
        lineNoStart = 1
        LineNos = true
        lineNumbersInTable = false
        noClasses = false
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
        unnumbered = false

[params]
    centerTheme = true
    favicon = '/static/images/favicon.ico'
    showBreadCrumbs = true
    toc = true

[params.git_info]
    host = "github"
    user = "remoterabbit"
    repo = "remoterabbit.github.io"
